### ISSUE TITLE
schedule cron batch property documentation misleading

### ISSUE THREAD

**Issue by jrb-github** [MicrosoftDocs/azure-devops-yaml-schema#158]
The documentation for the batch property reads:

> Whether to run the pipeline if the previously scheduled run is in-progress; the default is false.

This part:

> Whether to run the pipeline if the previously scheduled run is in-progress

suggests that you should set it to `true` if you want a new instance of the pipeline to start while the previously scheduled run is in progress.  However, the name of the parameter suggests otherwise.  I believe setting it to `true` actually specifies to not allow a new instance to start while the previously scheduled run is in progress, but am not completely clear on this without testing it myself.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 251b71d4-0c7c-bf2f-2da7-625d13d8aa2e
* Version Independent ID: 251b71d4-0c7c-bf2f-2da7-625d13d8aa2e
* Content: [schedules.cron definition](https://learn.microsoft.com/en-us/azure/devops/pipelines/yaml-schema/schedules-cron?view=azure-pipelines-2022)
* Content Source: [content/schedules-cron.md](https://github.com/MicrosoftDocs/azure-devops-yaml-schema/blob/main/content/schedules-cron.md)
* Service: **azure-devops-pipelines**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by WilliamAntonRohm** [comment]
@jrb-github -- thank you for your feedback and research.  Please clarify the product issue, and I will create a bug for you here:
- [Developer Community](https://developercommunity.visualstudio.com/AzureDevOps)


@steved0x -- please look into this issue.

**Comment by jrb-github** [comment]
@WilliamAntonRohm - Thanks for the response.  From the documentation it sounds like either `batch: true` or `batch: false` on a YAML schedule (ambiguious which one) is supposed to yield behavior where only one scheduled build is running at a time (presumably based on the latest source, either at the time it is starts, or is queued), regardless of whether the builds take longer to complete than the scheduling interval.  That is not the case.

**Comment by WilliamAntonRohm** [comment]
@jrb-github -- thank you for your follow-up.

**Comment by steved0x** [comment]
@jrb-github with batching, there should only ever be 1 running per branch, and when it completes, then only the most recent of the stacked runs would then run (since it represents the most recent version, for that branch). Let me build a repro scenario and I will file a product bug. And then I will try and word that property description better as I agree with your feedback (and now I want to go and check the batch property description for CI trigger to ensure it isn't worded the same).

**Comment by steved0x** [comment]
@jrb-github I have reached out to the author of this feature to get a clarification.

**Comment by steved0x** [comment]
@jrb-github I have gotten some details back. There is a bug filed on the behavior of the batch property. I don't have any updates for now (it is still in progress), but I am tracking the bug and I am finding out if I can put a note in the article to let folks know to set the batch=false for now until it is resolved.

**Comment by steved0x** [comment]
@jrb-github OK I have gotten an update from the product team. Cron schedules are intended to be sufficiently spaced so that potential batching does not play a role. The `always` property can be set to `false` to optimize the number of builds, if the code hasn't changed. I have been directed to remove `batch` from the documentation, as it is intended for CI triggres only, and does not work with respect to scheduled triggers. 

The guidance for now is to remove `batch` from your scheduled triggers (which is the equivalent of setting it to `false`) and we will update the documentation to reflect that.

There is currently a feature request for this, here: https://developercommunity.visualstudio.com/t/Cron-schedule-in-yaml-doesnt-respect-ba/10128592?q=cron+batch

Please go there and upvote this discussion. If this feature/fix is implemented, it will be for Azure DevOps Services only (and then any Azure DevOps Server versions that are released after that).

**Comment by jrb-github** [comment]
That is unfortunate, but reasonable, thanks for the follow-up Steve.

**Comment by steved0x** [comment]
@jrb-github The Azure Pipelines team made an update to batch for YAML scheduled triggers that just deployed as part of Azure DevOps sprint 224:
https://learn.microsoft.com/en-us/azure/devops/release-notes/2023/sprint-224-update#updates-to-yaml-cron-schedules

The doc should be live momentarily here:
https://learn.microsoft.com/en-us/azure/devops/pipelines/yaml-schema/schedules-cron?view=azure-pipelines

| Always | Batch | Behavior |
|--------|-------|----------|
| `false` | `false` | Pipeline runs only if there's a change with respect to the last successful scheduled pipeline run. |
| `false` | `true` | Pipeline runs only if there's a change with respect to the last successful scheduled pipeline run, and there's no in-progress scheduled pipeline run. |
| `true` | `false` | Pipeline runs according to the cron schedule. |
| `true` | `true` | Pipeline runs according to the cron schedule. |
