### ISSUE TITLE
Some properties lacking detail and defaults 

### ISSUE THREAD

**Issue by PJBowron** [MicrosoftDocs/azure-devops-yaml-schema#20]
Re: the `clean` property:
"Scorch the repo before fetching?" isn't very informative :)
Does it issue a "git clean"? With what params?

Also, the description for this property doesn't indicate what the default value is. Several other properties don't have their defaults indicated either.

Thank you.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b28abf7f-ecdf-8037-acd9-722690424372
* Version Independent ID: b28abf7f-ecdf-8037-acd9-722690424372
* Content: [steps.checkout definition](https://docs.microsoft.com/en-us/azure/devops/pipelines/yaml-schema/steps-checkout?view=azure-pipelines&source=docs)
* Content Source: [content/steps-checkout.md](https://github.com/MicrosoftDocs/azure-devops-yaml-schema/blob/main/content/steps-checkout.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by steved0x** [comment]
@PJBowron That is one of the unusual ones in there. These descriptions come from the schema that is used for validating the YAML Pipeline editor, for example:

https://github.com/microsoft/azure-pipelines-vscode/blob/282970bd18b11fe3da3b8c450ee15715b60ac9e4/service-schema.json#L3353

Unfortunately this schema doesn't include all of the defaults, and since this reference is generated from the schema, it doesn't include them. We are about to roll out an update to the engine that generates this documentation, and one improvement will be the ability to add in richer property descriptions to include things like defaults more easily.

There is more information on cleaning options here:
https://docs.microsoft.com/en-us/azure/devops/pipelines/process/phases?view=azure-devops&tabs=yaml#workspace

But that article doesn't explicitly say what the checkout clean does. When checkout clean is true, it runs `git clean -ffdx` followed by `git reset --hard HEAD` before fetching. 

I'll get that updated both here and in that other article. Thank you for letting us know.
