### ISSUE TITLE
deployType is documented as Required on SqlAzureDacpacDeployment@1

### ISSUE THREAD

**Issue by noontz** [MicrosoftDocs/azure-devops-yaml-schema#247]
deployType - Deploy type
Input alias: TaskNameSelector. string. **Required**. Allowed values: DacpacTask (SQL DACPAC File), SqlTask (SQL Script File), InlineSqlTask (Inline SQL Script). Default value: DacpacTask.

deployType is specified as **Required**

This task runs just fine without it:
task: SqlAzureDacpacDeployment@1
  displayName: Execute Azure SQL DacpacTask
  inputs:
    ConnectedServiceNameARM: Portal
    ServerName: $(SERVER-NAME)
    ${{ if eq(variables['Build.SourceBranchName'], 'main') }}:
      DatabaseName: production
    ${{ else }}:
      DatabaseName: staging
    SqlUsername: $(USER-NAME)
    SqlPassword: $(PASS-WORD)
    DacpacFile: $(System.DefaultWorkingDirectory)\bin\Release\SQL.dacpac

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: ddb32280-1779-eb6e-0f78-8707be623a9a
* Version Independent ID: ddb32280-1779-eb6e-0f78-8707be623a9a
* Content: [SqlAzureDacpacDeployment@1 - Azure SQL Database deployment v1 task](https://learn.microsoft.com/en-us/azure/devops/pipelines/tasks/reference/sql-azure-dacpac-deployment-v1?view=azure-pipelines)
* Content Source: [task-reference/sql-azure-dacpac-deployment-v1.md](https://github.com/MicrosoftDocs/azure-devops-yaml-schema/blob/main/task-reference/sql-azure-dacpac-deployment-v1.md)
* Service: **azure-devops-pipelines**
* Sub-service: **azure-devops-pipelines-tasks**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by steved0x** [comment]
@noontz   Thank you for your note. I can see your point - there are several other tasks with inputs like this - they are marked as required, but they also have a default value, so if they are left out, the default value is used. 

The task documentation is generated from the task source code, and since this input is marked as required in the task, the automated tooling that generates these articles marks it as required in the documentation. The built-in tasks are open source, and here is the line for the required attribute for this input:

https://github.com/microsoft/azure-pipelines-tasks/blob/master/Tasks/SqlAzureDacpacDeploymentV1/task.json#L176

```
        {
            "name": "TaskNameSelector",
            "aliases": [
                "deployType"
            ],
            "type": "pickList",
            "label": "Deploy type",
            "required": true,
            "helpMarkDown": "",
            "groupName": "taskDetails",
            "defaultValue": "DacpacTask",
            "options": {
                "DacpacTask": "SQL DACPAC File",
                "SqlTask": "SQL Script File",
                "InlineSqlTask": "Inline SQL Script"
            }
        },
```

The way to remove the required attribute from the documentation is to remove it from the task in the open source tasks repo linked above. You can submit a PR to the task (or file a GitHub issue [here](https://github.com/microsoft/azure-pipelines-tasks/issues)) to remove this required attribute along with your justification, and if the PR is accepted, the change will automatically be reflected in the docs. 

I can't change it in the docs, because the change would be overwritten the next time the automated tooling was run the refresh the task documentation, which uses the attributes from the task source for the [autogenerated portions of the task documentation](https://github.com/MicrosoftDocs/azure-devops-yaml-schema/blob/main/README.md#contributing-to-the-tasks-content).).

However, yours is not the only issue that has come up recently about required inputs that have defaults. I feel this is an issue that needs some more thought. I am going to create a work item to think about ways to handle this - maybe marking as required isn't the right option if there is a default. If we are able to make this change in our task documentation tooling, all of the task articles will be updated automatically.

Thank you,
Steve
