### ISSUE TITLE
Confused by DownloadPipelineArtifact input definitions

### ISSUE THREAD

**Issue by champnic** [MicrosoftDocs/azure-devops-yaml-schema#248]
Hello!

I'm confused by a couple of things on the documentation for DownloadPipelineArtifact page:
1. buildType/source is listed as 'required', but then has a default value described. When does the default value come into play if it's required, or is it optional?
2. buildType lists source as an alias, but then in the rest of the documentation just uses source. I think source should be the top-level described param, and buildType as the alias.
3. definition/pipeline and buildId/pipelineId are confusing, in that pipeline and pipelineId feel like they are the same thing? And it's unclear if I need to specify a definition/pipeline if I give a pipelineId, as the pipelineId is distinctly unique as far as I can tell. Do I need both?
4. Is there a difference between buildVersionToDownload and source being specific?
5. There is a 'downloadType' input described here: https://learn.microsoft.com/en-us/azure/devops/pipelines/artifacts/build-artifacts?view=azure-devops&tabs=yaml#download-artifacts, but I don't see it on the ref docs. Does it exist?

Sorry for all of these questions! I'm learning as I go :)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 6d5753b5-d4e7-6696-0230-3595f632ba0e
* Version Independent ID: 6d5753b5-d4e7-6696-0230-3595f632ba0e
* Content: [DownloadPipelineArtifact@2 - Download Pipeline Artifacts v2 task](https://learn.microsoft.com/en-us/azure/devops/pipelines/tasks/reference/download-pipeline-artifact-v2?view=azure-pipelines)
* Content Source: [task-reference/download-pipeline-artifact-v2.md](https://github.com/MicrosoftDocs/azure-devops-yaml-schema/blob/main/task-reference/download-pipeline-artifact-v2.md)
* Service: **azure-devops-pipelines**
* Sub-service: **azure-devops-pipelines-tasks**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by WilliamAntonRohm** [comment]
@champnic -- Nic, thank you for your feedback.  Please consider these resources:
- [Azure DevOps Services](https://azure.microsoft.com/support/devops/) 
- [Azure DevOps on Stack Overflow](https://stackoverflow.com/questions/tagged/azure-devops)

@steved0x -- Steve, please look into this issue.

**Comment by steved0x** [comment]
@champnic All good questions, let me try and provide some more information.
 
> 1. buildType/source is listed as 'required', but then has a default value described. When does the default value come into play if it's required, or is it optional?

This is a good question (a lot of folks have had this same question) - if a parameter has a default value, why is it required, because if it is omitted, the default value will be used. There are a couple of answers. The first is that the task reference documentation is built using the open source code for the tasks. Here is the section for the input that you reference:

https://github.com/microsoft/azure-pipelines-tasks/blob/3627dc980b124d513d9571d7bad486ce3bd6af46/Tasks/DownloadPipelineArtifactV2/task.json#L28

```
            "name": "source",
            "aliases": [
                "buildType"
            ],
            "type": "radio",
            "label": "Download artifacts produced by",
            "defaultValue": "current",
            "required": true,
            "options": {
                "current": "Current run",
                "specific": "Specific run"
            },
            "helpMarkDown": "Download artifacts produced by the current pipeline run, or from a specific pipeline run."
```

Since we go by the task source, if they mark it as required, the docs mark it as required.

The second answer, is that in some cases, it is possible to delete out the default value when editing the task in the [task assistant](https://learn.microsoft.com/en-us/azure/devops/pipelines/get-started/yaml-pipeline-editor?view=azure-devops#use-task-assistant). If that happens, the pipeline editor uses the required attribute to indicate an error in the pipeline editor. That really only comes into play if it is a text field in the task assistant.

In this particular example, it is a radio button with a default value in the task assistant, with no way to "un-select" a value. So an even stronger argument could be made that this parameter is not "required" since it is impossible to "un-select" it in the task assistant.

For now, the task documentation just follows the value of the "required" property in the task source code, but we looking at ways to screen it out for properties like this one.

> 2. buildType lists source as an alias, but then in the rest of the documentation just uses source. I think source should be the top-level described param, and buildType as the alias.

I agree. When `source` was added as an alias for `buildType`, it actually got added as the primary name, and `buildType` was moved to alias. (See the [Git blame](https://github.com/microsoft/azure-pipelines-tasks/blame/3627dc980b124d513d9571d7bad486ce3bd6af46/Tasks/DownloadPipelineArtifactV2/task.json#L21). Read [here](https://learn.microsoft.com/en-us/azure/devops/pipelines/tasks/reference/?view=azure-pipelines#what-are-task-input-aliases) for some background history on task aliases, but basically, aliases are used when a "more descriptive" name needs to be added to a task input, while preserving backwards compatibility with the previous name. Since the "alias" is intended to provide a more descriptive/better name, the task assistant, pipeline editor, and docs use the "alias" as the primary name. To update this, the name and alias would need to be swapped in the task source code. I recommend you file an issue with your feedback on the naming of this task input here: https://github.com/microsoft/azure-pipelines-tasks/issues

> 3. definition/pipeline and buildId/pipelineId are confusing, in that pipeline and pipelineId feel like they are the same thing? And it's unclear if I need to specify a definition/pipeline if I give a pipelineId, as the pipelineId is distinctly unique as far as I can tell. Do I need both?

`pipeline` is the pipeline definition, and `pipelineId` is a specific run of the pipeline. I will add some commentary to these parameters to call out the differences explicitly (they are very similarly named and with the aliases added, they could probably use some clarification)

If you specify `source == specific` you need to specify the `definition` (alias `pipeline`) which is the ID for the pipeline definition.

If you specify both `source == specific && runVersion == specific` then you also need the specific run `pipelineId' (or `runId/buildId`). The internals of the task could probably look up the `definition` but it doesn't so it has to be specified as well.

> 4. Is there a difference between buildVersionToDownload and source being specific?

They go together, if you specify a specific build ( `source == specific`), then you use `buildVersionToDownload` to specify where to get the specific run from, (latest, latestFromBranch, and specific). If you choose `specific` for `buildVersionToDownload`, the `pipelineID` property designates the pipeline run to get the artifacts from. If you specify one of the other two, then other properties provide information about them. If you go into the task assistant and make choices, you can see the UI change to present the different options that apply for that option. The "Required when  `source == specific && runVersion == specific`" type descriptions in the parameters provide that dependency information for folks using YAML instead of the task assistant.



> 5. There is a 'downloadType' input described here: https://learn.microsoft.com/en-us/azure/devops/pipelines/artifacts/build-artifacts?view=azure-devops&tabs=yaml#download-artifacts, but I don't see it on the ref docs. Does it exist?

That example is for the [Download**Build**Artifacts](https://learn.microsoft.com/en-us/azure/devops/pipelines/tasks/reference/download-build-artifacts-v1?view=azure-pipelines) task, which does a similar thing but is a different task.

Pipeline artifacts (and the Download/Publish PipelineArtifacts tasks) are available in Azure DevOps Services only, while Publish/Download Build Artifacts tasks can be used in Azure DevOps Services. If you are using Azure DevOps Services, you should use the "Pipeline" Artifacts versions of the tasks.

That is mentioned in the article you linked, but I can add a note the Download/Publish "Build" versions of the tasks.

> 
> Sorry for all of these questions! I'm learning as I go :)

Good questions!

I will make the updates I have mentioned today and they should be live shortly.

**Comment by champnic** [comment]
Fantastic, thanks so much for all of the info here @steved0x!!! And for the helpful links for the future @WilliamAntonRohm! Really appreciate the support :)
