### ISSUE TITLE
Reference for the top-level `name` is missing

### ISSUE THREAD

**Issue by MarkusBrgr** [MicrosoftDocs/azure-devops-yaml-schema#26]
The YAML schema reference does not list the `name:` keyword, from which you are able to name the pipeline-runs like the following:

`name:  $(BuildDefinitionName)_$(SourceBranchName)_$(Date:yyyyMMdd)$(rev:.rr)`

It is only mentioned in the [Build Number Section](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/run-number?view=azure-devops&tabs=yaml)

Is this the only missing keyword, or are maybe others also missing?

Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9316a0c0-9ccb-7bca-390f-771c9baa4e8d
* Version Independent ID: 9316a0c0-9ccb-7bca-390f-771c9baa4e8d
* Content: [YAML schema reference](https://docs.microsoft.com/en-us/azure/devops/pipelines/yaml-schema/?view=azure-pipelines&viewFallbackFrom=azure-devops)
* Content Source: [content/index.md](https://github.com/MicrosoftDocs/azure-devops-yaml-schema/blob/main/content/index.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by steved0x** [comment]
@MarkusBrgr The name property is a string property of the root pipeline, and is covered in the different pipeline representations here:

https://docs.microsoft.com/en-us/azure/devops/pipelines/yaml-schema/pipeline?view=azure-pipelines

Since YAML pipelines don't explicitly contain the keyword `pipeline` at the top, the YAML starts out with properties that describe the pipeline. Many of these properties are objects, like resources, triggers, and pools (which have their own reference page since they are objects) and some properties like name and lockBehavior are strings, and don't get a page; they just get a section in the YAML syntax block and the properties table of pipeline. Let me see if I can make that more clear in the documentation.

Thank you for the feedback!
