### ISSUE TITLE
Conflicting information from other learn page for same task

### ISSUE THREAD

**Issue by ocean-sm** [MicrosoftDocs/azure-devops-yaml-schema#43]
Hi team.

Why does this detail differ from: https://learn.microsoft.com/en-us/azure/devops/pipelines/tasks/utility/download-pipeline-artifact?view=azure-devops ?

In particular the "pipelineId" input string is added on this page, but it referenced as "pipeline" on the above link.
The examples also reference the "pipeline" input, not "pipelineId".

Thanks

---
#### Document details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 6d5753b5-d4e7-6696-0230-3595f632ba0e
* Version Independent ID: 6d5753b5-d4e7-6696-0230-3595f632ba0e
* Content: [DownloadPipelineArtifact@2 - Download Pipeline Artifacts v2 task](https://learn.microsoft.com/en-gb/azure/devops/pipelines/tasks/reference/download-pipeline-artifact-v2?view=azure-pipelines)
* Content Source: [task-reference/download-pipeline-artifact-v2.md](https://github.com/MicrosoftDocs/azure-devops-yaml-schema/blob/main/task-reference/download-pipeline-artifact-v2.md)
* Product: **devops**
* Technology: **devops-cicd-tasks**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by WilliamAntonRohm** [comment]
@ocean-sm -- thank you for your feedback.  Please note in that article under [Arguments](https://learn.microsoft.com/en-us/azure/devops/pipelines/tasks/utility/download-pipeline-artifact#arguments):
- `pipeline` Build Pipeline | (Required) The definition ID of the build pipeline.  Argument aliases: `definition`
- `runId` Build | (Required) The build from which to download the artifacts. For example: 1764  Argument aliases: `pipelineId`, `buildId`

I hope this helps answer your question.  I am closing this issue now, and you are welcome to @ mention me for any followup.  We hope to hear from you again.

**Comment by ocean-sm** [comment]
@WilliamAntonRohm - Thanks for the clarification... If I had read that properly, I guess I would have seen that, but I was already confused.

Why would two different articles outlining the same feature show different alias's?
Also, the main confusion comes from between the articles, pipeline says "the definition ID" whereas definition suggest "build pipeline name". Which is it - The ID or the name, or in this context the ID is the name?

We are using runVersion with latestFromBranch so the pipelineId is now understood to be irrelevant, so I now understand the difference, but the changing alias in the articles didn't help.

We currently us 'pipeline' in our task with the ID of the build pipeline, but wanted to use name if possible and this is where the confusion came from.
Thanks

**Comment by WilliamAntonRohm** [comment]
@ocean-sm -- thank you for your followup.  I agree that the overlap could be confusing.

@steved0x -- can you address their questions in the second paragraph above?

**Comment by steved0x** [comment]
@ocean-sm Thank you for posting this. I agree that those are two very similarly named input parameters, and I can see the confusion with promoting different input aliases as the "primary" alias. Each task input has a "Friendly name" used in the task assistant/classic designer, and then a "code" name used behind the scenes. For the first6 or so years of tasks, only the "Friendly name" was used. When the YAML pipelines were introduced, in some cases the "code" name wasn't user friendly and didn't clearly denote the intent of the input, so aliases were introduced so that "friendlier code names" could be added.

The original hand authored documentation had these aliases added over time, and not in any specific order. Sometimes the alias is given as the primary name and sometimes it is the original code name. The new task reference always the alias (if present) as the "primary" code name, since that matches the validation provided by the YAML schema used to validate the pipelines in the pipeline editor. Plus it (usually) maps to the better name that matches the intent of the input.

>We are using runVersion with latestFromBranch so the pipelineId is now understood to be irrelevant, so I now understand the difference, but the changing alias in the articles didn't help.
>
>We currently us 'pipeline' in our task with the ID of the build pipeline, but wanted to use name if possible and this is where the confusion came from.

If you are using buildType: specific, and buildVersionToDownload: latestFromBranch, you should be able to use definition: PipelineName (I can feel your confusion as these names are different than the original task reference, or the examples, which were migrated from the original task reference)

Did you still have a question there, or was it just the alias switching?

If you have any feedback or ideas for the presentation of the code name + aliases, that would be great. We are still landing the format of this new task reference. Maybe there is a way to feature the all the code names at the same level in the inputs presentation. Same idea for the YAML snippet at the top (which part of the documentation do you tend to go to first? Do you use the task assistant, or do you type in/copy paste the YAML?)

Thank you!
Steve

**Comment by ocean-sm** [comment]
Thanks @steved0x for the detailed response.
To answer your question, I don't have any other specific question thank you.

What you say makes sense and I do understand, and as I have got more experience with using and managing tasks, it is becoming clearer.

The main feedback still is that every time I want to do something different as part of our deployment, I research the tasks and ways to use them creatively to achieve what we need, but I continually come up against multiple pages for the same task as we have discussed above. Some times articles are published across different areas, and in some cases link directly across changing the entire area and menu, so I often have 10 or more tabs open trying to understand one parameter and how to use it with its various friendly names or alias, or a combination of.
Sometime the descriptions of the input parameters doesn't explain enough for more novice users, such as resources.pipelines.pipeline (https://learn.microsoft.com/en-us/azure/devops/pipelines/yaml-schema/resources-pipelines-pipeline?view=azure-pipelines) where it suggests the pipeline string is the ID of the resource. ID would usually imply a number or GUID, but in my use of it, it is just a descriptive name and not used for anything. Personally I did spend some extra thought processes working out what it needed to be.
I know that you cannot show examples for everyone's environments, but sometimes the examples do not show the use of all of the parameters and I am still guessing if the combination will work correctly.
I do try to where possible utilising the friendly task names, as they are usually more consistent, but sometime I just find myself hunting for a bash|powershell|script option to achieve my task.

As a side note, is there a roadmap for upcoming tasks or task versions?
For example, I would be keen to find out if the Kubernetes@1 will support replace or patch in the future.

Thanks for your time.

**Comment by steved0x** [comment]
@ocean-sm I don't know of a task roadmap, but you can sometimes get clues from looking in the open source repo for the tasks:

https://github.com/microsoft/azure-pipelines-tasks

Search the GH issues can sometimes reveal if other folks are asking the same thing and based on the replies, and if not, you could file an issue and ask if these features are forthcoming?

We are about to publish an update to the YAML schema part of the reference (that includes the example you mentioned above) that will support greater property descriptions, vs the autogenerated stubs that it gets from the source. That will allow us to improve descriptions like the one you mention.

**Comment by steved0x** [comment]
I am updating the example code in this article so that it is consistent with the YAML snippet.
