### ISSUE TITLE
AdditionalArguments - Unsatisfactory explanation of a list of variables

### ISSUE THREAD

**Issue by terafirma92** [MicrosoftDocs/azure-devops-yaml-schema#47]
AdditionalArguments - This is list of variables that can be inputted, there is no way to know what these variables are since there is no supporting documentation linked and there is no way to search in your documentation or on google to get an answer.

A link to supporting documenation that explains what can be input here would allow developers to easily find what they need.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 189a26b0-6c82-2222-a63b-90e6e0ddd540
* Version Independent ID: 189a26b0-6c82-2222-a63b-90e6e0ddd540
* Content: [IISWebAppDeploymentOnMachineGroup@0 - IIS web app deploy v0 task](https://learn.microsoft.com/en-us/azure/devops/pipelines/tasks/reference/iisweb-app-deployment-on-machine-group-v0?view=azure-pipelines)
* Content Source: [task-reference/iisweb-app-deployment-on-machine-group-v0.md](https://github.com/MicrosoftDocs/azure-devops-yaml-schema/blob/main/task-reference/iisweb-app-deployment-on-machine-group-v0.md)
* Product: **devops**
* Technology: **devops-cicd-tasks**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by steved0x** [comment]
@terafirma92 I apologize that this issue was in the backlog for so long. The task uses Microsoft Web Deploy, and these are the different settings available for the `additionalArguments` section:

https://learn.microsoft.com/en-us/previous-versions/windows/it-pro/windows-server-2008-R2-and-2008/dd569089(v=ws.10)

I am updating the task article today. Thank you for letting us know.

Steve
