### ISSUE TITLE
Show usage for a repository reference to a tag and indicate if wildcards can be used.

### ISSUE THREAD

**Issue by jdholbrook81** [MicrosoftDocs/azure-devops-yaml-schema#6]
Documentation shows you can reference a branch, but does not show using tags which is possible. Include usage examples. Also indicate if wildcards can be used and provide an example if so. I'm trying to reference tags with the format Major.Minor.Patch by using ref: refs/tags/1.* and it is failing.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9fb0ba85-0e96-cb7a-6984-0ab15823ea32
* Version Independent ID: 9fb0ba85-0e96-cb7a-6984-0ab15823ea32
* Content: [resources.repositories.repository definition](https://docs.microsoft.com/en-us/azure/devops/pipelines/yaml-schema/resources-repositories-repository?view=azure-pipelines)
* Content Source: [content/resources-repositories-repository.md](https://github.com/MicrosoftDocs/azure-devops-yaml-schema/blob/main/content/resources-repositories-repository.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by asdkant-bf** [comment]
When I try to use a tag as the ref of a repo resource, Azure Pipelines appends `refs/heads/` no matter what syntax I use, and this is driving me insane because it breaks what I'm trying to do.

**Comment by steved0x** [comment]
@jdholbrook81

The wildcards should be the same as described here:
https://docs.microsoft.com/en-us/azure/devops/pipelines/repos/azure-repos-git?view=azure-devops&tabs=yaml#wildcards

And referencing the branches should be the same as here:
https://docs.microsoft.com/en-us/azure/devops/pipelines/repos/azure-repos-git?view=azure-devops&tabs=yaml#tags

I will update the article to call these out - if you have any trouble, please reply here, or if this issue is closed (I will link it to the PR that makes these updates) please open a new one and let us know which parts aren't working.

Thank you
